services:
  db:
    image: postgres:15-alpine
    container_name: abelo_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./abelo_test_app
    container_name: abelo_fastapi
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      - db

volumes:
  postgres_data:
